### ISSUE TITLE
Add support for projects

### ISSUE THREAD

**Issue by pimentel** [AtomLinter/linter-lintr#12] opened 2015-12-11 19:46 UTC
Thanks so much for making this work!

It would be cold to have project specific configurations with different linters.

I am not sure what would be required since I haven't really used AtomLinter very much, but if no 1 takes a stab at it, I can probably look it over the holiday break.

cheers

**Comment by Arcanemagus** [comment] 2015-12-11 19:50
Duplicate of https://github.com/atom-community/linter/issues/744, this would need to be handled at the `linter` level, not a plugin (like this project). Feel free to contribute to that discussion, it's quite a complex issue though.

**Closed by Arcanemagus** 2015-12-11 19:50 UTC

**Comment by jimhester** [comment] 2015-12-11 21:15
@pimentel lintr already looks for a `.lintr` file in your current directory or package root directory (if you are developing a package). (https://github.com/jimhester/lintr#project-configuration).

However I believe this will not work with the Atom plugin as written, as the file passed to the R process is a temporary file so will not be looking in the proper directory.

It would require changes to the plugin as well as lintr itself to implement properly I opened https://github.com/jimhester/lintr/issues/123 to track this.
